### ISSUE TITLE
Error while installing ukfast/safedns v1.1.2: checksum list has unexpected SHA-256 hash

### ISSUE THREAD

**Issue by djalertive** [ukfast/terraform-provider-safedns#6]
When attempting to use v1.1.2 of the plugin e.g.

`safedns = {
      source = "ukfast/safedns"
      version = "1.1.2"
    }`

Then running terraform init, i'm receiving the following error:

> Error: Failed to install provider
> 
> Error while installing ukfast/safedns v1.1.2: checksum list has unexpected
> SHA-256 hash 1ed01664ddfd8b63d298110ed27f40b5e9d8d7ac408b7323fd52fa77f8d33980
> (expected 7a1fea04bdcfeadbbf317603451ece83b374325a5d9442718d142fb989c2953f)

**Comment by 0x4c6565** [comment]
Hi @djalertive - this provider has been moved over to the `ans-group` organisation, however it would appear the redirect is broken.

I would recommend updating your provider reference whilst we look into this:

https://registry.terraform.io/providers/ans-group/safedns/1.1.3

**Comment by djalertive** [comment]
Thanks for the quick response @0x4c6565, updating to the following resulted in the terraform init completing without error:

`safedns = {
      source = "ans-group/safedns"
    }
`

**Comment by rcunningham-cr** [comment]
@0x4c6565 any chance this can be updated within README or updating the registry docs to reflect this?

**Comment by 0x4c6565** [comment]
> @0x4c6565 any chance this can be updated within README or updating the registry docs to reflect this?

Added to readme @rcunningham-cr:

https://github.com/ans-group/terraform-provider-safedns/blob/master/README.md#upgrading
